### ISSUE TITLE
GitHub Actions Image Artifacts have expired and the Qt customization is missing.

### ISSUE THREAD

**Issue by CyberDuck79** [Seeed-Studio/meta-seeed-cm4#11]
- The pre-built images have expired.
-  I'm not sure if this is the right place, but it is missing in the Seeed documentation explanations of how to embed your own QT app in Yocto.

**Comment by bigbearishappy** [comment]
Sorry for my late reply. You can download the latest release image of reTerminal in [here](https://github.com/Seeed-Studio/meta-seeed-cm4/releases)
About the embedding QT app in yocto, you can get the detail in this [bb file](https://github.com/Seeed-Studio/meta-seeed-cm4/blob/main/recipes-qtdemo/reterminal/reterminalqt5example_git.bb)
