### ISSUE TITLE
Upgrade meta-qt5 => meta-qt6

### ISSUE THREAD

**Issue by matthiasklein** [Seeed-Studio/meta-seeed-cm4#14]
Are there any plans to switch from meta-qt5 to meta-qt6?

**Comment by bigbearishappy** [comment]
Thank you for your suggestion.We will have a try to upgrade to meta-qt6 soon.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
