### ISSUE TITLE
Issues with Default Yocto System Image

### ISSUE THREAD

**Issue by lakshanthad** [Seeed-Studio/meta-seeed-cm4#2]
The following are the issues when running the latest system image on reTerminal:

- [x] UART doesnt work
- [x] "i2cdetect -l" doesnt work after turning on reTerminal. It works only when "modprobe i2c-dev" command is executed after each boot
- [x] #dtparam=i2c_arm=on is like this when first boot. But if the above "modprobe i2c-dev" command is executed, I2C works, even though it is turned off from config.txt
- [x] spidev_test tool not working. It needs to be put inside the system image and recompile
- [x] CSI Camera need 3rd party software to work
- [x] Micro-HDMI hot-plug feature not working
- [x] Add Python package and reTerminal Python Library into the system image
- [x] Add pip package to system image
- [x] #3
- [x] Make "python3" available in both "python3" and "python"
- [x] Add reTerminal Python Library into the system image - https://github.com/Seeed-Studio/Seeed_Python_ReTerminal
- [ ] When Qt demo is running, HDMI hot plug does not work
- [ ] When connected to HDMI, Qt demo orientation on HDMI display is not correct

**Comment by lakshanthad** [comment]
Thank you @bigbearishappy . I have tested the above and the issues have been resolved.

However, I found 2 new issues. Please check.

Thank you.

**Comment by embetrix** [comment]
I built a pri test image from dunfell branch, it doesn't look that's working !!

**Comment by embetrix** [comment]
you are nowhere defining MACHINE=seeed-reterminal to build !!!!

**Comment by bigbearishappy** [comment]
> I built a pri test image from dunfell branch, it doesn't look that's working !!

Can you tell me the detail of the problem with you image(LCD not working or somethine else)?. I can help you to fix them.

**Comment by bigbearishappy** [comment]
> you are nowhere defining MACHINE=seeed-reterminal to build !!!!

The source code of seeed-reterminal is in [here](https://github.com/Seeed-Studio/meta-seeed-cm4/blob/dunfell/conf/machine/seeed-reterminal.conf).
You can take a look in it.

**Comment by embetrix** [comment]
yes it's there but you didn't defined it anywhere in your build script nor in action script file

**Comment by embetrix** [comment]
an Image built with yocto doesn't start at all nothing!!
I tried the buildroot image it's working.

do you have any yocto image to download ?

your CI jobs doesn't work neither !

it's a big frustration, your HW spec looks great but on other hand the software...let's stay polite.!

**Comment by bigbearishappy** [comment]
> 

I see.I will try to fix the github action and let you know.
Thank you for your reminder.

**Comment by bigbearishappy** [comment]
@embexus 
You can download the firmware from github action now.
Please unzip the yocto deplay.zip you downloaded and use the file rpi-test-image-seeed-reterminal-20220506191438.rootfs.wic.bz2 to flash your reterminal.

**Comment by embetrix** [comment]
@bigbearishappy : thanks this image seems to be working, can you please simplify or document the build procedure, because we may want to build an image without github actions ?

**Comment by embetrix** [comment]
@bigbearishappy : with this image the serial output is also not working !!

I checked that in config.txt:
```
#dtparam=pwr_led_gpio=35
# Enable I2C
dtparam=i2c1=on
dtparam=i2c_arm=on
# Enable UART
enable_uart=1
# Enable VC4 Graphics
dtoverlay=vc4-kms-v3d

dtoverlay=vc4-kms-v3d-pi4
dtoverlay=reTerminal,tp_rotate=1
dtoverlay=dwc2,dr_mode=host

```

I think the problem I had yersterday is that I built a console image, so the serial was not outputting anything.

probably you have a miss-configured device tree ?

**Comment by bigbearishappy** [comment]
> @bigbearishappy : thanks this image seems to be working, can you please simplify or document the build procedure, because we may want to build an image without github actions ?

[Here](https://wiki.seeedstudio.com/reTerminal-Yocto/) is the detail step of compiling on your own computer.

**Comment by bigbearishappy** [comment]
> @bigbearishappy : with this image the serial output is also not working !!
> 
> I checked that in config.txt:
> 
> ```
> #dtparam=pwr_led_gpio=35
> # Enable I2C
> dtparam=i2c1=on
> dtparam=i2c_arm=on
> # Enable UART
> enable_uart=1
> # Enable VC4 Graphics
> dtoverlay=vc4-kms-v3d
> 
> dtoverlay=vc4-kms-v3d-pi4
> dtoverlay=reTerminal,tp_rotate=1
> dtoverlay=dwc2,dr_mode=host
> ```
> 
> I think the problem I had yersterday is that I built a console image, so the serial was not outputting anything.
> 
> probably you have a miss-configured device tree ?

I will fix the uart issue and let you know.

**Comment by embetrix** [comment]
@bigbearishappy 

I created a file in the boot partition cmdline.txt with following content:

```
console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 loglevel=7 vt.global_cursor_default=0 consoleblank=0 fbcon=rotate:1
```

i can see serial output now :-)

you can add it to machine configuration :

```
CMDLINE_append = " console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 loglevel=7 vt.global_cursor_default=0 consoleblank=0 fbcon=rotate:1"
```

**Comment by embetrix** [comment]
maybe add also **fbcon=rotate:1** should fix the screen orientation ;-)

**Comment by bigbearishappy** [comment]
> @bigbearishappy
> 
> I created a file in the boot partition cmdline.txt with following content:
> 
> ```
> console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 loglevel=7 vt.global_cursor_default=0 consoleblank=0 fbcon=rotate:1
> ```
> 
> i can see serial output now :-)
> 
> you can add it to machine configuration :
> 
> ```
> CMDLINE_append = " console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 loglevel=7 vt.global_cursor_default=0 consoleblank=0 fbcon=rotate:1"
> ```

That's great.I'll try it.
Thank you.

**Comment by bigbearishappy** [comment]
@embexus I remember that I have already try to rotate the LCD with fbcon=rotate... Unfortunately,it didn't work.
Because this feature only work when the LCD support rotate register.
And the problem about the uart.I just fix it. you can download the latest firmware in [here](https://github.com/Seeed-Studio/meta-seeed-cm4/actions/runs/2367016730)
