### ISSUE TITLE
ParseError at dnfdragora_2.1.2.bb

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/meta-seeed-cm4#4]
I tring to compile yocto source code for reTerminal.
I are running this procedure.
https://wiki.seeedstudio.com/reTerminal-Yocto/#compile-yocto-source-code

After Step 15 `bitbake rpi-test-image`, I got error.
```
ERROR: ParseError at /home/matsujirushi/poky/meta-openembedded/meta-oe/recipes-graphics/dnfdragora/dnfdragora_2.1.2.bb:16: Could not inherit file classes/setuptools3-base.bbclass
```
![image](https://user-images.githubusercontent.com/8079404/154893589-76d173b5-43e9-40a1-a419-36cdbf635a18.png)

How to fix?

**Comment by bigbearishappy** [comment]
> I tring to compile yocto source code for reTerminal. I are running this procedure. https://wiki.seeedstudio.com/reTerminal-Yocto/#compile-yocto-source-code
> 
> After Step 15 `bitbake rpi-test-image`, I got error.
> 
> ```
> ERROR: ParseError at /home/matsujirushi/poky/meta-openembedded/meta-oe/recipes-graphics/dnfdragora/dnfdragora_2.1.2.bb:16: Could not inherit file classes/setuptools3-base.bbclass
> ```
> 
> ![image](https://user-images.githubusercontent.com/8079404/154893589-76d173b5-43e9-40a1-a419-36cdbf635a18.png)
> 
> How to fix?

Hello, Sorry to see this. And the wiki is too old to use.
it's better for you to follow the github action source code [here](https://github.com/Seeed-Studio/meta-seeed-cm4/blob/7c846e23de9346d318fbdc8ac92dcc72b90fb6ce/.github/workflows/yocto-dunfell.yml#L148)

**Comment by lakshanthad** [comment]
@matsujirushi I will update with new compilation instructions on the wiki. In the meantime, @bigbearishappy will help us reproduce the issue and find a solution to the problem.

**Comment by matsujirushi** [comment]
Hi @bigbearishappy ,
I ran it with reference to the GitHub action source code.
The following error has occurred.
```
matsujirushi@mj-yocto:~/poky/build$ bitbake rpi-test-image
ERROR: ParseError at /home/matsujirushi/poky/meta/recipes-multimedia/gstreamer/gstreamer1.0-python_1.20.0.bb:30: Could not inherit file classes/setuptools3-base.bbclass
```

Command history is:
```
   26  git clone -b master git://git.yoctoproject.org/poky
   27  cd poky
   28  cp -r meta/recipes-multimedia/gstreamer/ ../
   29  git checkout dunfell
   30  rm -r meta/recipes-multimedia/gstreamer/
   31  cp -r ../gstreamer/ meta/recipes-multimedia/
   32  rm -r ../gstreamer/
   33  git diff .
   34  git clone -b dunfell https://github.com/Seeed-Studio/meta-seeed-reterminal.git
   35  cp meta-seeed-reterminal/build-*.sh ./
   36  rm -rf meta-seeed-reterminal/
   37  chmod +x build-*.sh
   38  ./build-reterminal-image.sh
   39  cd
   40  ls
   41  cd poky
   42  source oe-init-build-env
   43  bitbake rpi-test-image
```

Do you notice anything?

**Comment by bigbearishappy** [comment]
> 



> Hi @bigbearishappy , I ran it with reference to the GitHub action source code. The following error has occurred.
> 
> ```
> matsujirushi@mj-yocto:~/poky/build$ bitbake rpi-test-image
> ERROR: ParseError at /home/matsujirushi/poky/meta/recipes-multimedia/gstreamer/gstreamer1.0-python_1.20.0.bb:30: Could not inherit file classes/setuptools3-base.bbclass
> ```
> 
> Command history is:
> 
> ```
>    26  git clone -b master git://git.yoctoproject.org/poky
>    27  cd poky
>    28  cp -r meta/recipes-multimedia/gstreamer/ ../
>    29  git checkout dunfell
>    30  rm -r meta/recipes-multimedia/gstreamer/
>    31  cp -r ../gstreamer/ meta/recipes-multimedia/
>    32  rm -r ../gstreamer/
>    33  git diff .
>    34  git clone -b dunfell https://github.com/Seeed-Studio/meta-seeed-reterminal.git
>    35  cp meta-seeed-reterminal/build-*.sh ./
>    36  rm -rf meta-seeed-reterminal/
>    37  chmod +x build-*.sh
>    38  ./build-reterminal-image.sh
>    39  cd
>    40  ls
>    41  cd poky
>    42  source oe-init-build-env
>    43  bitbake rpi-test-image
> ```
> 
> Do you notice anything?

Hello. Sorry for my late reply.
I have just fixed the compile error and the make the firmware work fine.
Now, there is no need to change the repo of [poky](git://git.yoctoproject.org/poky). We need to change the kernel version from
5.4 to 5.10 on branch dunfell of [meta-raspberrypi](git://git.yoctoproject.org/meta-raspberrypi).
if you want to get more detail of the change.
you can see the following commit on branch dunfell:
[5cd6a98f294566393a8460f6fe14f747a9b3f33b](https://github.com/Seeed-Studio/meta-seeed-cm4/commit/5cd6a98f294566393a8460f6fe14f747a9b3f33b)
[01414c020f2676add7772dec5d5ef7b777899edd](https://github.com/Seeed-Studio/meta-seeed-cm4/commit/01414c020f2676add7772dec5d5ef7b777899edd)

Please let me know if you have any problem.

**Comment by lakshanthad** [comment]
@matsujirushi Please wait for me. I will update wiki according to the above fix and let you know so that you can follow it.

**Comment by lakshanthad** [comment]
@matsujirushi 

Please refer to the following updated wiki:
https://wiki.seeedstudio.com/reTerminal-Yocto

Better to clear browser cache or open in private browsing. Otherwise you might not see the changes.

**Comment by matsujirushi** [comment]
Hi @lakshanthad ,
I create an OS image using the wiki page as a reference.
But there is two problem.

1. The display is rotated 90 degrees.
![image](https://user-images.githubusercontent.com/8079404/156970420-60281016-cd7d-4cb4-bf59-b9a4052979f9.png)

2. Touch is not responding. Touch several times to stop Qt application.
![image](https://user-images.githubusercontent.com/8079404/156970526-5392047c-86cf-4204-a210-6b4e7a070c30.png)

Do these not occur in your reTerminal?

**Comment by bigbearishappy** [comment]
> Hi @lakshanthad , I create an OS image using the wiki page as a reference. But there is two problem.
> 
> 1. The display is rotated 90 degrees.
>    ![image](https://user-images.githubusercontent.com/8079404/156970420-60281016-cd7d-4cb4-bf59-b9a4052979f9.png)
> 2. Touch is not responding. Touch several times to stop Qt application.
>    ![image](https://user-images.githubusercontent.com/8079404/156970526-5392047c-86cf-4204-a210-6b4e7a070c30.png)
> 
> Do these not occur in your reTerminal?

I have just fixed this two problem. you can try to modify the source file of the qt5 demo by referring this [commit](https://github.com/Seeed-Studio/Seeed_Python_ReTerminalQt5Examples/commit/9b34d86aa8319be44721dd281c6f8fd92b8744be).
Or you can rebuild your yocto firmware with the latest qt demo.

**Comment by matsujirushi** [comment]
Hi @bigbearishappy ,
It is working. 😍
Thank you.

![image](https://user-images.githubusercontent.com/8079404/157167606-e76ca97a-6641-446b-a104-0fe6408f4f4a.png)

![image](https://user-images.githubusercontent.com/8079404/157167621-19b2fa87-9f56-4eaa-b6ba-9393fc440b5c.png)
