### ISSUE TITLE
dynamically pulling the device tree fails

### ISSUE THREAD

**Issue by TheYoctoJester** [Seeed-Studio/meta-seeed-cm4#8]
```
| --2022-05-18 19:10:26--  https://raw.githubusercontent.com/Seeed-Studio/seeed-linux-dtoverlays/master/overlays/rpi/reTerminal-overlay.dts
| Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
| wget: unable to resolve host address ‘raw.githubusercontent.com’
| WARNING: exit code 4 from a shell command.
```

I am aware that this is probably being caused by deliberate decisions for the layer, so I do not expect a fix. But it should be noted that this is caused by the kernel recipe trying to pull specific files from an upstream kernel recipe.

**Comment by bigbearishappy** [comment]
we can not use the wget in the do_configure task in kirkstone now.it's a new feature of kirkstone.We can only access the network in th do_fetch task.
You can have a try with this [link](https://github.com/agherzan/meta-raspberrypi/issues/1063)
If you have any problem, please let me know.
Thank you.

**Comment by bigbearishappy** [comment]
I have just fix this problem. You can sync the code to your own repo and compile it.
If you have any problem, you can reopen this issue and let me know.
