### ISSUE TITLE
Missing drivers for accelerometer, light sensor, physical buttons

### ISSUE THREAD

**Issue by aanrudolph2** [Seeed-Studio/meta-seeed-cm4#9]
It appears that the setup script for Raspberry Pi OS uses DKMS to install driver support for LIS3DHTR (Accelerometer). I'm not sure how the physical buttons are set up, but they also work on Raspberry Pi OS. Neither of these function when running a Yocto build. I followed the instructions at https://raymii.org/s/tutorials/Yocto_boot2qt_for_the_Seeed_reTerminal_qt6.html and https://raymii.org/s/tutorials/Yocto_boot2qt_for_the_Raspberry_Pi_4_both_Qt_6_and_Qt_5.html, and cross-referenced them with the "official" Yocto instructions at https://wiki.seeedstudio.com/reTerminal-Yocto/ (there doesn't seem to be much difference except the addition of Boot2Qt).

Can someone please confirm this is missing, or point me in the right direction to get the buttons and accelerometer working?

**Comment by aanrudolph2** [comment]
Update: tried official instructions for building. Light Sensor and Accelerometer drivers are *not* present in layer. Demo application correctly shows accelerometer data, but does not appear to show correct light sensor data. I confirmed that the drivers are absent. Physical buttons *do* work.

**Comment by bigbearishappy** [comment]
So, now the problem is the light sensor is not working right? How do you confirm that the light sensor driver is absent?
